---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-infra
  timeout: 20s
  url: ssh://git@git.dev1.zeppi.tech:2222/root/flux-infra.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev1.zeppi.tech
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./dev1.zeppi.tech
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infra

