apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/reference/dynamic-configuration/kubernetes-crd-definition.yml
- traefik.rbac.yaml
- traefik.pvc.yaml
- traefik.yaml
- whoami.yaml
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.13.1/controller.yaml
